---
title: "Solomon Islands"
author: "Yingmai Chen"
output: html_document
runtime: shiny
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
library(shiny)
library(leaflet)
library(sf)

```
```{r echo=FALSE,message=FALSE,warning=FALSE}
solomon_islands <- st_read("solomon islands.geojson")
```

```{r echo=FALSE,warning=FALSE}
ui <- fluidPage(
    titlePanel("Map of the Solomon Islands"),
    leafletOutput("map")
)

server <- function(input, output) {
    output$map <- renderLeaflet({
        leaflet(data = solomon_islands) %>%
            addTiles() %>%
            addPolygons()
    })
}

shinyApp(ui = ui, server = server)
```
First,I create a map to show the geographical position of the solomon islands.I frame its position in blue.data is from
(https://github.com/glynnbird/countriesgeojson/blob/master/solomon%20islands.geojson)

```{r echo=FALSE}
ui <- fluidPage(
    titlePanel("Key Facts About the Solomon Islands"),
    sidebarLayout(
        sidebarPanel(
            checkboxGroupInput("factsToShow", "Select Facts to Show", 
                               choices = c("Location", "Major Islands", "Capital", "Area", "Population", "Language", "Independence"))
        ),
        mainPanel(
            uiOutput("selectedFacts")
        )
    )
)

server <- function(input, output) {
    output$selectedFacts <- renderUI({
        facts <- list(
            Location = "Southwestern Pacific Ocean",
            `Major Islands` = "6 major and over 900 smaller islands",
            Capital = "Honiara, located on Guadalcanal",
            Area = "Approximately 29,000 square kilometers",
            Population = "About 700,000",
            Language = "English, Pijin",
            Independence = "Obtained from the United Kingdom in 1978"
        )
        
        selectedFacts <- lapply(input$factsToShow, function(fact) {
            wellPanel(
                h4(fact),
                p(facts[[fact]])
            )
        })
        
        do.call(tagList, selectedFacts)
    })
}

shinyApp(ui = ui, server = server)


```

Then I show some key features for the solomon islands.Data(https://en.wikipedia.org/wiki/Solomon_Islands)


